#ifndef USB_DESCRIPTORS_HPP
#define USB_DESCRIPTORS_HPP

#include <Adafruit_TinyUSB.h>
#include "./deck_config.hpp"

// Common
#define DECK_USB_VID 0x0fd9
#define DECK_USB_MANUFACTURER "Elgato Systems GmbH"

#define OUTPUT_REPORT_ID  2
#define OUTPUT_REPORT_LEN 1023

#define KEY_IMAGE_SIZE_BYTES (KEY_IMAGE_SIZE * KEY_IMAGE_SIZE * 3)

#ifdef DECK_TOUCH
  #define TOUCHSCREEN_SIZE_BYTES (TOUCHSCREEN_PIXEL_WIDTH * TOUCHSCREEN_PIXEL_HEIGHT * 3)
#else
  #define TOUCHSCREEN_SIZE_BYTES 0
#endif

#if KEY_IMAGE_SIZE_BYTES > TOUCHSCREEN_SIZE_BYTES
  #define MAX_IMAGE_SIZE_BYTES KEY_IMAGE_SIZE_BYTES
#else
  #define MAX_IMAGE_SIZE_BYTES TOUCHSCREEN_SIZE_BYTES
#endif

#define KEY_COUNT KEY_COUNT_COL * KEY_COUNT_ROW

#define INPUT_REPORT_FLAGS   HID_DATA | HID_VARIABLE | HID_ABSOLUTE | HID_WRAP_NO | HID_LINEAR | HID_PREFERRED_STATE | HID_NO_NULL_POSITION
#define OUTPUT_REPORT_FLAGS  HID_DATA | HID_VARIABLE | HID_ABSOLUTE | HID_WRAP_NO | HID_LINEAR | HID_PREFERRED_STATE | HID_NO_NULL_POSITION | HID_NON_VOLATILE
#define FEATURE_REPORT_FLAGS HID_DATA | HID_ARRAY    | HID_RELATIVE | HID_WRAP_NO | HID_LINEAR | HID_PREFERRED_STATE | HID_NO_NULL_POSITION | HID_NON_VOLATILE
#define REPORT_FIELD()  HID_LOGICAL_MIN  ( 0 ), HID_LOGICAL_MAX_N  ( 0xFF, 2 ), HID_REPORT_SIZE  ( 8 ), 

#define TUD_HID_REPORT_DESC() \
HID_USAGE_PAGE ( HID_USAGE_PAGE_CONSUMER    ), \
HID_USAGE      ( HID_USAGE_CONSUMER_CONTROL ), \
HID_COLLECTION ( HID_COLLECTION_APPLICATION ), \
  /** Uses Vendor Page for whole collection unless redefined. **/ \
  HID_USAGE_PAGE_N(HID_USAGE_PAGE_VENDOR, 2),  \
  REPORT_FIELD() \
    /* reset, image, etc... */ \
    HID_REPORT_COUNT_N ( OUTPUT_REPORT_LEN, 2), \
    HID_REPORT_ID    ( OUTPUT_REPORT_ID ) \
    HID_USAGE ( HID_USAGE_CONSUMER_CONTROL ), \
    HID_OUTPUT       ( OUTPUT_REPORT_FLAGS ) ,\
    \
    /* keys, touchscreen, dials */ \
    HID_REPORT_COUNT ( INPUT_REPORT_LEN ), \
    HID_REPORT_ID    ( 0x01 ) \
    HID_USAGE ( HID_USAGE_CONSUMER_CONTROL ), \
    HID_INPUT        ( INPUT_REPORT_FLAGS ), \
    \
    /* reset */ \
    HID_REPORT_COUNT ( 31 ), \
    HID_REPORT_ID    (0x03) \
    HID_USAGE ( HID_USAGE_CONSUMER_CONTROL ), \
    HID_FEATURE      ( FEATURE_REPORT_FLAGS ), \
    \
    /* version */ \
    HID_REPORT_COUNT ( 31 ), \
    HID_REPORT_ID    (0x05) \
    HID_USAGE ( HID_USAGE_CONSUMER_CONTROL ), \
    HID_FEATURE      ( FEATURE_REPORT_FLAGS ), \
    \
    /* serial */ \
    HID_REPORT_COUNT ( 31 ), \
    HID_REPORT_ID    (0x06) \
    HID_USAGE ( HID_USAGE_CONSUMER_CONTROL ), \
    HID_FEATURE      ( FEATURE_REPORT_FLAGS ), \
HID_COLLECTION_END

#endif // USB_DESCRIPTORS_HPP
